// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://busihcyxjrzqmuafiytm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1c2loY3l4anJ6cW11YWZpeXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTA4NTYsImV4cCI6MjA2NjI2Njg1Nn0.PGzu5P98brRQ51Z6FzI1zBtOXx52TYrUumN_L2gTXtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);